Service: passthrough

PreDeploy: preDeploy.py

Stacks:
  Global:
    Tags:
      Name: $SERVICE-$STAGE
      Owner: WSE
      Contact: web-and-software-engineering-group@nd.edu
      InceptDate: $TIMESTAMP
  Single:
    - Name: $SERVICE-$STAGE
      Template: root.yml
      Tags:
        Description: Passthrough responsible for attaching API Keys to Primo API queries
      Parameters:
        Stage: $STAGE
        ServiceName: $SERVICE
        ServiceStage: $SERVICE-$STAGE
        TemplateBucket: $DEPLOY_BUCKET
        TemplateFolder: $DEPLOY_FOLDER
        PassthroughUrl: ${PASSTHROUGH_URL}
        PrimoApiKey: ${PRIMO_API_KEY}
        Version: dev

Artifacts:
  Templates:
    - root.yml
    - lambda.yml
    - api.yml

  Zips:
    - Name: Passthrough
      Files:
        - ../index.js
        - ../node_modules

LambdaEnv:
  Global:
    KMSKey: alias/wse/kms/
  Single:
    - FunctionName: $SERVICE-$STAGE-passthrough
      Environment:
        -
          Name: PRIMO_API_KEY
          Value: ${PRIMO_API_KEY}
        -
          Name: PASSTHROUGH_URL
          Value: ${PASSTHROUGH_URL}
